[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
private_a = "6rVFHSb2cqn1VXB9iE9P8nRxdTP3mbgGFZfwXDz2Q7c9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/elizabeth/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
